[EnableEpochs]
    # BLSMultiSignerEnableEpoch represents the activation epoch for different types of BLS multi-signers
    BLSMultiSignerEnableEpoch = [
        { EnableEpoch = 0, Type = "KOSK"}
    ]

    # MaxNodesChangeEnableEpoch holds configuration for changing the maximum number of nodes and the enabling epoch
    MaxNodesChangeEnableEpoch = [
        { EpochEnable = 0, MaxNumNodes = 56, NodesToShufflePerShard = 2 }
    ]

[GasSchedule]
    # GasScheduleByEpochs holds the configuration for the gas schedule that will be applied from specific epochs
    GasScheduleByEpochs = [
        { StartEpoch = 0, FileName = "gasScheduleV7.toml" },
    ]
