NumMainShards = 3

SubscribedAddresses = ["erd1qqqqqqqqqqqqqpgqt6ltx52ukss9d2qag2k67at28a36xc9lkp2sr06394"]

[WebSocket]
    Url = "localhost:10001"
    # Possible values: json, gogo protobuf. Should be compatible with mx-chain-node outport driver config
    MarshallerType = "gogo protobuf"
    # Retry duration (receive/send ack signal) in seconds
    RetryDuration = 5
    # Signals if in case of data payload processing error, we should send the ack signal or not
    BlockingAckOnError = false
