NumMainShards = 1

SubscribedAddresses = ["erd1qyu5wthldzr8wx5c9ucg8kjagg0jfs53s8nr3zpz3hypefsdd8ssycr6th"]

[WebSocket]
    Url = "localhost:22111"
    # Possible values: json, gogo protobuf. Should be compatible with mx-chain-node outport driver config
    MarshallerType = "gogo protobuf"
    # Retry duration (receive/send ack signal) in seconds
    RetryDuration = 5
    # Signals if in case of data payload processing error, we should send the ack signal or not
    BlockingAckOnError = false
    # Possible values: sha256, keccak, blake2b. Should be compatible with mx-chain-node outport driver config
    HasherType = "blake2b"
