SubscribedEvents = [
    { Identifier = "deposit", Addresses = ["erd1qqqqqqqqqqqqqpgqtpvpj5udf7rjjddkvpa3uuqrpnekxm27pr9syaut7c"] }
]

[WebSocket]
    Url = "localhost:22111" #ip from the observer
    # Possible values: json, gogo protobuf. Should be compatible with mx-chain-node outport driver config
    MarshallerType = "gogo protobuf"
    # Retry duration (receive/send ack signal) in seconds
    RetryDuration = 5
    # Signals if in case of data payload processing error, we should send the ack signal or not
    BlockingAckOnError = false
    # Possible values: sha256, keccak, blake2b. Should be compatible with mx-chain-node outport driver config
    HasherType = "blake2b"
    # This flag describes the mode to start the WebSocket connector. Can be "client" or "server"
    Mode = "client"
    # This flag specifies if we should send an acknowledge signal upon receiving data
    WithAcknowledge = true
    # The duration in seconds to wait for an acknowledgement message
    AcknowledgeTimeout = 60
    # Payload version to process
    Version = 1
