[ExtendedShardHdrNonceHashStorage]
    [ExtendedShardHdrNonceHashStorage.Cache]
        Name = "ExtendedShardHdrNonceHashStorage"
        Capacity = 1000
        Type = "SizeLRU"
        SizeInBytes = 3145728 #3MB
    [ExtendedShardHdrNonceHashStorage.DB]
        FilePath = "ExtendedShardHdrNonceHash"
        Type = "LvlDBSerial"
        BatchDelaySeconds = 2
        MaxBatchSize = 100
        MaxOpenFiles = 10


[ExtendedShardHeaderStorage]
    [ExtendedShardHeaderStorage.Cache]
        Name = "ExtendedShardHeaderStorage"
        Capacity = 1000
        Type = "SizeLRU"
        SizeInBytes = 3145728 #3MB
    [ExtendedShardHeaderStorage.DB]
        FilePath = "ExtendedShardHeader"
        Type = "LvlDBSerial"
        BatchDelaySeconds = 2
        MaxBatchSize = 100
        MaxOpenFiles = 10

[MainChainNotarization]
    # This defines the starting round from which all sovereign chain nodes should starting notarizing main chain headers
    MainChainNotarizationStartRound = 11

[OutgoingSubscribedEvents]
    # Time to wait in seconds for outgoing operations that need to be bridged from sovereign chain to main chain.
    # If no confirmation of bridged data is received after this time, next leader should retry sending data.
    TimeToWaitForUnconfirmedOutGoingOperation = 30

    SubscribedEvents = [
    { Identifier = "bridgeOps", Addresses = ["erd1qyu5wthldzr8wx5c9ucg8kjagg0jfs53s8nr3zpz3hypefsdd8ssycr6th"] }
]
