name: Build

on:
  pull_request:
    branches: [master, rc/*]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, macos-13-xlarge]
    runs-on: ${{ matrix.runs-on }}
    name: Build
    steps:
      - name: Set up Go 1.20.7
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.7
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      - name: Build
        run: |
          cd ${GITHUB_WORKSPACE}/cmd/node && go build .
          cd ${GITHUB_WORKSPACE}/cmd/seednode && go build .
          cd ${GITHUB_WORKSPACE}/cmd/keygenerator && go build .
          cd ${GITHUB_WORKSPACE}/cmd/logviewer && go build .
          cd ${GITHUB_WORKSPACE}/cmd/termui && go build .

      - name: Smoke test
        run: |
          ${GITHUB_WORKSPACE}/cmd/node --help
          ${GITHUB_WORKSPACE}/cmd/seednode --help
          ${GITHUB_WORKSPACE}/cmd/keygenerator --help
          ${GITHUB_WORKSPACE}/cmd/logviewer --help
          ${GITHUB_WORKSPACE}/cmd/termui --help
