name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master, feat/*, rc/* ]

permissions:
  contents: read

jobs:
  trivy:
    name: Run trivy scanner
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
